package deri.sensor.meta;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * @author Hoan Nguyen Mau Quoc
 */
public class Country_Continent {
	public static Map<String,String> continents_shortname_map = new HashMap<String,String>(10);
	public static Map<String,String> countries_shortname_map = new HashMap<String,String>(300);
	public static Map<String,List<String>> continents_countries_map = new HashMap<String,List<String>>(10);
	public static Map<String,String> countries_lowercase_continents_map = new HashMap<String,String>(250);
	public static List<String> continents_list = new ArrayList<String>(7);
	public static List<String> countries_list = new ArrayList<String>(250);
	public static List<String> countries_list_lowercase = new ArrayList<String>(250);
	
	public static List<String> AS= new ArrayList<String>(50);
	public static List<String> NA= new ArrayList<String>(50);
	public static List<String> SA= new ArrayList<String>(50);
	public static List<String> EU= new ArrayList<String>(50);
	public static List<String> AF= new ArrayList<String>(50);
	public static List<String> OC= new ArrayList<String>(5);
	public static List<String> AN= new ArrayList<String>(10);
	
	static{
		initialize_AS();
		initialize_NA();
		initialize_SA();
		initialize_EU();
		initialize_AF();
		initialize_OC();
		initialize_AN();
		
		initialize_countries_map();
		initialize_continents_map();
		initialize_continents_countries_map();
		initialize_countries_continents_map();
		initialize_continents_list();
		initialize_countries_list();
		initialize_countries_list_lowercase();
	}
	
	private static void initialize_AS(){
		AS.add("Iran");
		AS.add("Iraq");
		AS.add("Azerbaijan");
		AS.add("Armenia");
		AS.add("Israel");
		AS.add("Bahrain");
		AS.add("United Arab Emirates");
		AS.add("Georgia");
		AS.add("Afghanistan");
		AS.add("India");
		AS.add("Bangladesh");
		AS.add("Indonesia");
		AS.add("Bhutan");
		AS.add("China");
		AS.add("Hong Kong");
		AS.add("Brunei");
		AS.add("Christmas Island");
		AS.add("Saudi Arabia");
		AS.add("Syria");
		AS.add("Jordan");
		AS.add("Lebanon");
		AS.add("Palestinian Territory");
		AS.add("Kuwait");
		AS.add("Oman");
		AS.add("Qatar");
		AS.add("Kazakhstan");
		AS.add("Pakistan");
		AS.add("Thailand");
		AS.add("Tajikistan");
		AS.add("Malaysia");
		AS.add("Kyrgyzstan");
		AS.add("Sri Lanka");
		AS.add("Maldives");
		AS.add("Nepal");
		AS.add("Myanmar");
		AS.add("Mongolia");
		AS.add("Laos");
		AS.add("Philippines");
		AS.add("Macao");
		AS.add("Cambodia");
		AS.add("South Korea");
		AS.add("Japan");
		AS.add("North Korea");
		AS.add("Singapore");
		AS.add("Yemen");
		AS.add("Turkmenistan");
		AS.add("Turkey");
		AS.add("Uzbekistan");
		AS.add("Vietnam");
		AS.add("Taiwan");
		AS.add("British Indian Ocean Territory");
	}
	
	private static void initialize_NA(){
		NA.add("Barbados");
		NA.add("Greenland");
		NA.add("Dominican Republic");
		NA.add("Netherlands Antilles");
		NA.add("Cuba");
		NA.add("Bahamas");
		NA.add("Bermuda");
		NA.add("Anguilla");
		NA.add("Dominica");
		NA.add("Antigua and Barbuda");
		NA.add("Aruba");
		NA.add("Guadeloupe");
		NA.add("Saint Barthelemy");
		NA.add("Grenada");
		NA.add("Belize");
		NA.add("Guatemala");
		NA.add("Honduras");
		NA.add("Costa Rica");
		NA.add("Haiti");
		NA.add("Canada");
		NA.add("Saint Pierre and Miquelon");
		NA.add("Mexico");
		NA.add("Jamaica");
		NA.add("Martinique");
		NA.add("Saint Kitts and Nevis");
		NA.add("Saint Lucia");
		NA.add("Turks and Caicos Islands");
		NA.add("Montserrat");
		NA.add("Saint Martin");
		NA.add("Cayman Islands");
		NA.add("El Salvador");
		NA.add("Nicaragua");
		NA.add("Panama");
		NA.add("Puerto Rico");
		NA.add("Trinidad and Tobago");
		NA.add("British Virgin Islands");
		NA.add("Saint Vincent and the Grenadines");
		NA.add("United States");
		NA.add("U.S. Virgin Islands");
		NA.add("United States Minor Outlying Islands");

	}
	
	private static void initialize_SA(){
		SA.add("Guyana");
		SA.add("French Guiana");
		SA.add("Brazil");
		SA.add("Falkland Islands");
		SA.add("Argentina");
		SA.add("Bolivia");
		SA.add("Ecuador");
		SA.add("Colombia");
		SA.add("Chile");
		SA.add("Suriname");
		SA.add("Paraguay");
		SA.add("Peru");
		SA.add("Uruguay");
		SA.add("Venezuela");
	}
	
	private static void initialize_EU(){
		EU.add("Cyprus");
		EU.add("Greece");
		EU.add("Albania");
		EU.add("Andorra");
		EU.add("Estonia");
		EU.add("Belarus");
		EU.add("Finland");
		EU.add("Hungary");
		EU.add("Bulgaria");
		EU.add("Gibraltar");
		EU.add("Spain");
		EU.add("Italy");
		EU.add("Austria");
		EU.add("Denmark");
		EU.add("Faroe Islands");
		EU.add("Iceland");
		EU.add("United Kingdom");
		EU.add("Ireland");
		EU.add("Switzerland");
		EU.add("Belgium");
		EU.add("Germany");
		EU.add("France");
		EU.add("Isle of Man");
		EU.add("Guernsey");
		EU.add("Czech Republic");
		EU.add("Croatia");
		EU.add("Bosnia and Herzegovina");
		EU.add("Russia");
		EU.add("Latvia");
		EU.add("Lithuania");
		EU.add("Sweden");
		EU.add("Moldova");
		EU.add("Romania");
		EU.add("Slovakia");
		EU.add("Poland");
		EU.add("Norway");
		EU.add("Serbia");
		EU.add("Kosovo");
		EU.add("Macedonia");
		EU.add("Portugal");
		EU.add("Malta");
		EU.add("Svalbard and Jan Mayen");
		EU.add("Netherlands");
		EU.add("Luxembourg");
		EU.add("Monaco");
		EU.add("Liechtenstein");
		EU.add("Jersey");
		EU.add("San Marino");
		EU.add("Slovenia");
		EU.add("Montenegro");
		EU.add("Ukraine");
		EU.add("Vatican");
		EU.add("Aaland Islands");
		EU.add("Serbia and Montenegro");
	}
	
	private static void initialize_AF(){
		AF.add("Angola");
		AF.add("Democratic Republic of the Congo");
		AF.add("Djibouti");
		AF.add("Central African Republic");
		AF.add("Ethiopia");
		AF.add("Eritrea");
		AF.add("Egypt");
		AF.add("Burundi");
		AF.add("Botswana");
		AF.add("Cameroon");
		AF.add("Republic of the Congo");
		AF.add("Ivory Coast");
		AF.add("Ghana");
		AF.add("Equatorial Guinea");
		AF.add("Burkina Faso");
		AF.add("Guinea-Bissau");
		AF.add("Benin");
		AF.add("Gabon");
		AF.add("Gambia");
		AF.add("Guinea");
		AF.add("Western Sahara");
		AF.add("Algeria");
		AF.add("Cape Verde");
		AF.add("Somalia");
		AF.add("Libya");
		AF.add("Kenya");
		AF.add("Rwanda");
		AF.add("Malawi");
		AF.add("Seychelles");
		AF.add("Chad");
		AF.add("Sudan");
		AF.add("Namibia");
		AF.add("Comoros");
		AF.add("Lesotho");
		AF.add("Mauritius");
		AF.add("Swaziland");
		AF.add("Reunion");
		AF.add("Mozambique");
		AF.add("Madagascar");
		AF.add("Senegal");
		AF.add("Liberia");
		AF.add("Nigeria");
		AF.add("Togo");
		AF.add("Mauritania");
		AF.add("Sierra Leone");
		AF.add("Sao Tome and Principe");
		AF.add("Niger");
		AF.add("Mali");
		AF.add("Morocco");
		AF.add("Saint Helena");
		AF.add("Tanzania");
		AF.add("Zambia");
		AF.add("Uganda");
		AF.add("Zimbabwe");
		AF.add("Mayotte");
		AF.add("South Africa");
		AF.add("Tunisia");
		
	}
	
	private static void initialize_OC(){
		OC.add("Micronesia");
		OC.add("Australia");
		OC.add("Fiji");
		OC.add("Cook Islands");
		OC.add("Guam");
		OC.add("American Samoa");
		OC.add("Palau");
		OC.add("Papua New Guinea");
		OC.add("Solomon Islands");
		OC.add("Kiribati");
		OC.add("Marshall Islands");
		OC.add("New Caledonia");
		OC.add("Norfolk Island");
		OC.add("New Zealand");
		OC.add("French Polynesia");
		OC.add("Pitcairn");
		OC.add("Niue");
		OC.add("Northern Mariana Islands");
		OC.add("East Timor");
		OC.add("Tuvalu");
		OC.add("Vanuatu");
		OC.add("Tonga");
		OC.add("Wallis and Futuna");
		OC.add("Samoa");
		OC.add("Cocos Islands");
		OC.add("Nauru");
		OC.add("Tokelau");
	}
	
	private static void initialize_AN(){
		AN.add("South Georgia and the South Sandwich Islands");
		AN.add("Antarctica");
		AN.add("French Southern Territories");
		AN.add("Heard Island and McDonald Islands");
		AN.add("Bouvet Island");
	}
	
	private static void initialize_countries_map(){
		countries_shortname_map.put("AD", "Andorra");
		countries_shortname_map.put("AE", "United Arab Emirates");
		countries_shortname_map.put("AF", "Afghanistan");
		countries_shortname_map.put("AG", "Antigua and Barbuda");
		countries_shortname_map.put("AI", "Anguilla");
		countries_shortname_map.put("AL", "Albania");
		countries_shortname_map.put("AM", "Armenia");
		countries_shortname_map.put("AN", "Netherlands Antilles");
		countries_shortname_map.put("AO", "Angola");
		countries_shortname_map.put("AQ", "Antarctica");
		countries_shortname_map.put("AR", "Argentina");
		countries_shortname_map.put("AS", "American Samoa");
		countries_shortname_map.put("AT", "Austria");
		countries_shortname_map.put("AU", "Australia");
		countries_shortname_map.put("AW", "Aruba");
		countries_shortname_map.put("AX", "Aaland Islands");
		countries_shortname_map.put("AZ", "Azerbaijan");
		countries_shortname_map.put("BA", "Bosnia and Herzegovina");
		countries_shortname_map.put("BB", "Barbados");
		countries_shortname_map.put("BD", "Bangladesh");
		countries_shortname_map.put("BE", "Belgium");
		countries_shortname_map.put("BF", "Burkina Faso");
		countries_shortname_map.put("BG", "Bulgaria");
		countries_shortname_map.put("BH", "Bahrain");
		countries_shortname_map.put("BI", "Burundi");
		countries_shortname_map.put("BJ", "Benin");
		countries_shortname_map.put("BL", "Saint Barthelemy");
		countries_shortname_map.put("BM", "Bermuda");
		countries_shortname_map.put("BN", "Brunei");
		countries_shortname_map.put("BO", "Bolivia");
		countries_shortname_map.put("BR", "Brazil");
		countries_shortname_map.put("BS", "Bahamas");
		countries_shortname_map.put("BT", "Bhutan");
		countries_shortname_map.put("BV", "Bouvet Island");
		countries_shortname_map.put("BW", "Botswana");
		countries_shortname_map.put("BY", "Belarus");
		countries_shortname_map.put("BZ", "Belize");
		countries_shortname_map.put("CA", "Canada");
		countries_shortname_map.put("CC", "Cocos Islands");
		countries_shortname_map.put("CD", "Democratic Republic of the Congo");
		countries_shortname_map.put("CF", "Central African Republic");
		countries_shortname_map.put("CG", "Republic of the Congo");
		countries_shortname_map.put("CH", "Switzerland");
		countries_shortname_map.put("CI", "Ivory Coast");
		countries_shortname_map.put("CK", "Cook Islands");
		countries_shortname_map.put("CL", "Chile");
		countries_shortname_map.put("CM", "Cameroon");
		countries_shortname_map.put("CN", "China");
		countries_shortname_map.put("CO", "Colombia");
		countries_shortname_map.put("CR", "Costa Rica");
		countries_shortname_map.put("CS", "Serbia and Montenegro");
		countries_shortname_map.put("CU", "Cuba");
		countries_shortname_map.put("CV", "Cape Verde");
		countries_shortname_map.put("CX", "Christmas Island");
		countries_shortname_map.put("CY", "Cyprus");
		countries_shortname_map.put("CZ", "Czech Republic");
		countries_shortname_map.put("DE", "Germany");
		countries_shortname_map.put("DJ", "Djibouti");
		countries_shortname_map.put("DK", "Denmark");
		countries_shortname_map.put("DM", "Dominica");
		countries_shortname_map.put("DO", "Dominican Republic");
		countries_shortname_map.put("DZ", "Algeria");
		countries_shortname_map.put("EC", "Ecuador");
		countries_shortname_map.put("EE", "Estonia");
		countries_shortname_map.put("EG", "Egypt");
		countries_shortname_map.put("EH", "Western Sahara");
		countries_shortname_map.put("ER", "Eritrea");
		countries_shortname_map.put("ES", "Spain");
		countries_shortname_map.put("ET", "Ethiopia");
		countries_shortname_map.put("FI", "Finland");
		countries_shortname_map.put("FJ", "Fiji");
		countries_shortname_map.put("FK", "Falkland Islands");
		countries_shortname_map.put("FM", "Micronesia");
		countries_shortname_map.put("FO", "Faroe Islands");
		countries_shortname_map.put("FR", "France");
		countries_shortname_map.put("GA", "Gabon");
		countries_shortname_map.put("GB", "United Kingdom");
		countries_shortname_map.put("GD", "Grenada");
		countries_shortname_map.put("GE", "Georgia");
		countries_shortname_map.put("GF", "French Guiana");
		countries_shortname_map.put("GG", "Guernsey");
		countries_shortname_map.put("GH", "Ghana");
		countries_shortname_map.put("GI", "Gibraltar");
		countries_shortname_map.put("GL", "Greenland");
		countries_shortname_map.put("GM", "Gambia");
		countries_shortname_map.put("GN", "Guinea");
		countries_shortname_map.put("GP", "Guadeloupe");
		countries_shortname_map.put("GQ", "Equatorial Guinea");
		countries_shortname_map.put("GR", "Greece");
		countries_shortname_map.put("GS", "South Georgia and the South Sandwich Islands");
		countries_shortname_map.put("GT", "Guatemala");
		countries_shortname_map.put("GU", "Guam");
		countries_shortname_map.put("GW", "Guinea-Bissau");
		countries_shortname_map.put("GY", "Guyana");
		countries_shortname_map.put("HK", "Hong Kong");
		countries_shortname_map.put("HM", "Heard Island and McDonald Islands");
		countries_shortname_map.put("HN", "Honduras");
		countries_shortname_map.put("HR", "Croatia");
		countries_shortname_map.put("HT", "Haiti");
		countries_shortname_map.put("HU", "Hungary");
		countries_shortname_map.put("ID", "Indonesia");
		countries_shortname_map.put("IE", "Ireland");
		countries_shortname_map.put("IL", "Israel");
		countries_shortname_map.put("IM", "Isle of Man");
		countries_shortname_map.put("IN", "India");
		countries_shortname_map.put("IO", "British Indian Ocean Territory");
		countries_shortname_map.put("IQ", "Iraq");
		countries_shortname_map.put("IR", "Iran");
		countries_shortname_map.put("IS", "Iceland");
		countries_shortname_map.put("IT", "Italy");
		countries_shortname_map.put("JE", "Jersey");
		countries_shortname_map.put("JM", "Jamaica");
		countries_shortname_map.put("JO", "Jordan");
		countries_shortname_map.put("JP", "Japan");
		countries_shortname_map.put("KE", "Kenya");
		countries_shortname_map.put("KG", "Kyrgyzstan");
		countries_shortname_map.put("KH", "Cambodia");
		countries_shortname_map.put("KI", "Kiribati");
		countries_shortname_map.put("KM", "Comoros");
		countries_shortname_map.put("KN", "Saint Kitts and Nevis");
		countries_shortname_map.put("KP", "North Korea");
		countries_shortname_map.put("KR", "South Korea");
		countries_shortname_map.put("XK", "Kosovo");
		countries_shortname_map.put("KW", "Kuwait");
		countries_shortname_map.put("KY", "Cayman Islands");
		countries_shortname_map.put("KZ", "Kazakhstan");
		countries_shortname_map.put("LA", "Laos");
		countries_shortname_map.put("LB", "Lebanon");
		countries_shortname_map.put("LC", "Saint Lucia");
		countries_shortname_map.put("LI", "Liechtenstein");
		countries_shortname_map.put("LK", "Sri Lanka");
		countries_shortname_map.put("LR", "Liberia");
		countries_shortname_map.put("LS", "Lesotho");
		countries_shortname_map.put("LT", "Lithuania");
		countries_shortname_map.put("LU", "Luxembourg");
		countries_shortname_map.put("LV", "Latvia");
		countries_shortname_map.put("LY", "Libya");
		countries_shortname_map.put("MA", "Morocco");
		countries_shortname_map.put("MC", "Monaco");
		countries_shortname_map.put("MD", "Moldova");
		countries_shortname_map.put("ME", "Montenegro");
		countries_shortname_map.put("MF", "Saint Martin");
		countries_shortname_map.put("MG", "Madagascar");
		countries_shortname_map.put("MH", "Marshall Islands");
		countries_shortname_map.put("MK", "Macedonia");
		countries_shortname_map.put("ML", "Mali");
		countries_shortname_map.put("MM", "Myanmar");
		countries_shortname_map.put("MN", "Mongolia");
		countries_shortname_map.put("MO", "Macao");
		countries_shortname_map.put("MP", "Northern Mariana Islands");
		countries_shortname_map.put("MQ", "Martinique");
		countries_shortname_map.put("MR", "Mauritania");
		countries_shortname_map.put("MS", "Montserrat");
		countries_shortname_map.put("MT", "Malta");
		countries_shortname_map.put("MU", "Mauritius");
		countries_shortname_map.put("MV", "Maldives");
		countries_shortname_map.put("MW", "Malawi");
		countries_shortname_map.put("MX", "Mexico");
		countries_shortname_map.put("MY", "Malaysia");
		countries_shortname_map.put("MZ", "Mozambique");
		countries_shortname_map.put("NA", "Namibia");
		countries_shortname_map.put("NC", "New Caledonia");
		countries_shortname_map.put("NE", "Niger");
		countries_shortname_map.put("NF", "Norfolk Island");
		countries_shortname_map.put("NG", "Nigeria");
		countries_shortname_map.put("NI", "Nicaragua");
		countries_shortname_map.put("NL", "Netherlands");
		countries_shortname_map.put("NO", "Norway");
		countries_shortname_map.put("NP", "Nepal");
		countries_shortname_map.put("NR", "Nauru");
		countries_shortname_map.put("NU", "Niue");
		countries_shortname_map.put("NZ", "New Zealand");
		countries_shortname_map.put("OM", "Oman");
		countries_shortname_map.put("PA", "Panama");
		countries_shortname_map.put("PE", "Peru");
		countries_shortname_map.put("PF", "French Polynesia");
		countries_shortname_map.put("PG", "Papua New Guinea");
		countries_shortname_map.put("PH", "Philippines");
		countries_shortname_map.put("PK", "Pakistan");
		countries_shortname_map.put("PL", "Poland");
		countries_shortname_map.put("PM", "Saint Pierre and Miquelon");
		countries_shortname_map.put("PN", "Pitcairn");
		countries_shortname_map.put("PR", "Puerto Rico");
		countries_shortname_map.put("PS", "Palestinian Territory");
		countries_shortname_map.put("PT", "Portugal");
		countries_shortname_map.put("PW", "Palau");
		countries_shortname_map.put("PY", "Paraguay");
		countries_shortname_map.put("QA", "Qatar");
		countries_shortname_map.put("RE", "Reunion");
		countries_shortname_map.put("RO", "Romania");
		countries_shortname_map.put("RS", "Serbia");
		countries_shortname_map.put("RU", "Russia");
		countries_shortname_map.put("RW", "Rwanda");
		countries_shortname_map.put("SA", "Saudi Arabia");
		countries_shortname_map.put("SB", "Solomon Islands");
		countries_shortname_map.put("SC", "Seychelles");
		countries_shortname_map.put("SD", "Sudan");
		countries_shortname_map.put("SE", "Sweden");
		countries_shortname_map.put("SG", "Singapore");
		countries_shortname_map.put("SH", "Saint Helena");
		countries_shortname_map.put("SI", "Slovenia");
		countries_shortname_map.put("SJ", "Svalbard and Jan Mayen");
		countries_shortname_map.put("SK", "Slovakia");
		countries_shortname_map.put("SL", "Sierra Leone");
		countries_shortname_map.put("SM", "San Marino");
		countries_shortname_map.put("SN", "Senegal");
		countries_shortname_map.put("SO", "Somalia");
		countries_shortname_map.put("SR", "Suriname");
		countries_shortname_map.put("ST", "Sao Tome and Principe");
		countries_shortname_map.put("SV", "El Salvador");
		countries_shortname_map.put("SY", "Syria");
		countries_shortname_map.put("SZ", "Swaziland");
		countries_shortname_map.put("TC", "Turks and Caicos Islands");
		countries_shortname_map.put("TD", "Chad");
		countries_shortname_map.put("TF", "French Southern Territories");
		countries_shortname_map.put("TG", "Togo");
		countries_shortname_map.put("TH", "Thailand");
		countries_shortname_map.put("TJ", "Tajikistan");
		countries_shortname_map.put("TK", "Tokelau");
		countries_shortname_map.put("TL", "East Timor");
		countries_shortname_map.put("TM", "Turkmenistan");
		countries_shortname_map.put("TN", "Tunisia");
		countries_shortname_map.put("TO", "Tonga");
		countries_shortname_map.put("TR", "Turkey");
		countries_shortname_map.put("TT", "Trinidad and Tobago");
		countries_shortname_map.put("TV", "Tuvalu");
		countries_shortname_map.put("TW", "Taiwan");
		countries_shortname_map.put("TZ", "Tanzania");
		countries_shortname_map.put("UA", "Ukraine");
		countries_shortname_map.put("UG", "Uganda");
		countries_shortname_map.put("UM", "United States Minor Outlying Islands");
		countries_shortname_map.put("US", "United States");
		countries_shortname_map.put("UY", "Uruguay");
		countries_shortname_map.put("UZ", "Uzbekistan");
		countries_shortname_map.put("VA", "Vatican");
		countries_shortname_map.put("VC", "Saint Vincent and the Grenadines");
		countries_shortname_map.put("VE", "Venezuela");
		countries_shortname_map.put("VG", "British Virgin Islands");
		countries_shortname_map.put("VI", "U.S. Virgin Islands");
		countries_shortname_map.put("VN", "Vietnam");
		countries_shortname_map.put("VU", "Vanuatu");
		countries_shortname_map.put("WF", "Wallis and Futuna");
		countries_shortname_map.put("WS", "Samoa");
		countries_shortname_map.put("YE", "Yemen");
		countries_shortname_map.put("YT", "Mayotte");
		countries_shortname_map.put("ZA", "South Africa");
		countries_shortname_map.put("ZM", "Zambia");
		countries_shortname_map.put("ZW", "Zimbabwe");
	}
	
	private static void initialize_continents_map(){
		continents_shortname_map.put("AS", "Asia");
		continents_shortname_map.put("NA", "North America");
		continents_shortname_map.put("EU", "Europe");
		continents_shortname_map.put("AF", "Africa");
		continents_shortname_map.put("AN", "Antarctica");
		continents_shortname_map.put("SA", "South America");
		continents_shortname_map.put("OC", "Oceania");
	}
	
	private static void initialize_continents_countries_map(){
		continents_countries_map.put("Asia", AS);
		continents_countries_map.put("North America", NA);
		continents_countries_map.put("Europe", EU);
		continents_countries_map.put("Africa", AF);
		continents_countries_map.put("Antarctica", AN);
		continents_countries_map.put("South America", SA);
		continents_countries_map.put("Oceania", OC);
	}
	
	private static void initialize_countries_continents_map(){
		countries_lowercase_continents_map.put("barbados", "North America");
		countries_lowercase_continents_map.put("greenland", "North America");
		countries_lowercase_continents_map.put("dominican republic", "North America");
		countries_lowercase_continents_map.put("netherlands antilles", "North America");
		countries_lowercase_continents_map.put("cuba", "North America");
		countries_lowercase_continents_map.put("bahamas", "North America");
		countries_lowercase_continents_map.put("bermuda", "North America");
		countries_lowercase_continents_map.put("anguilla", "North America");
		countries_lowercase_continents_map.put("dominica", "North America");
		countries_lowercase_continents_map.put("antigua and barbuda", "North America");
		countries_lowercase_continents_map.put("aruba", "North America");
		countries_lowercase_continents_map.put("guadeloupe", "North America");
		countries_lowercase_continents_map.put("saint barthelemy", "North America");
		countries_lowercase_continents_map.put("grenada", "North America");
		countries_lowercase_continents_map.put("belize", "North America");
		countries_lowercase_continents_map.put("guatemala", "North America");
		countries_lowercase_continents_map.put("honduras", "North America");
		countries_lowercase_continents_map.put("costa rica", "North America");
		countries_lowercase_continents_map.put("haiti", "North America");
		countries_lowercase_continents_map.put("canada", "North America");
		countries_lowercase_continents_map.put("saint pierre and miquelon", "North America");
		countries_lowercase_continents_map.put("mexico", "North America");
		countries_lowercase_continents_map.put("jamaica", "North America");
		countries_lowercase_continents_map.put("martinique", "North America");
		countries_lowercase_continents_map.put("saint kitts and nevis", "North America");
		countries_lowercase_continents_map.put("saint lucia", "North America");
		countries_lowercase_continents_map.put("turks and caicos islands", "North America");
		countries_lowercase_continents_map.put("montserrat", "North America");
		countries_lowercase_continents_map.put("saint martin", "North America");
		countries_lowercase_continents_map.put("cayman islands", "North America");
		countries_lowercase_continents_map.put("el salvador", "North America");
		countries_lowercase_continents_map.put("nicaragua", "North America");
		countries_lowercase_continents_map.put("panama", "North America");
		countries_lowercase_continents_map.put("puerto rico", "North America");
		countries_lowercase_continents_map.put("trinidad and tobago", "North America");
		countries_lowercase_continents_map.put("british virgin islands", "North America");
		countries_lowercase_continents_map.put("saint vincent and the grenadines", "North America");
		countries_lowercase_continents_map.put("united states", "North America");
		countries_lowercase_continents_map.put("u.s. virgin islands", "North America");
		countries_lowercase_continents_map.put("guyana", "South America");
		countries_lowercase_continents_map.put("french guiana", "South America");
		countries_lowercase_continents_map.put("brazil", "South America");
		countries_lowercase_continents_map.put("falkland islands", "South America");
		countries_lowercase_continents_map.put("argentina", "South America");
		countries_lowercase_continents_map.put("bolivia", "South America");
		countries_lowercase_continents_map.put("ecuador", "South America");
		countries_lowercase_continents_map.put("colombia", "South America");
		countries_lowercase_continents_map.put("chile", "South America");
		countries_lowercase_continents_map.put("suriname", "South America");
		countries_lowercase_continents_map.put("paraguay", "South America");
		countries_lowercase_continents_map.put("peru", "South America");
		countries_lowercase_continents_map.put("uruguay", "South America");
		countries_lowercase_continents_map.put("venezuela", "South America");
		countries_lowercase_continents_map.put("south georgia and the south sandwich islands", "Antarctica");
		countries_lowercase_continents_map.put("antarctica", "Antarctica");
		countries_lowercase_continents_map.put("french southern territories", "Antarctica");
		countries_lowercase_continents_map.put("micronesia", "Oceania");
		countries_lowercase_continents_map.put("australia", "Oceania");
		countries_lowercase_continents_map.put("fiji", "Oceania");
		countries_lowercase_continents_map.put("cook islands", "Oceania");
		countries_lowercase_continents_map.put("guam", "Oceania");
		countries_lowercase_continents_map.put("american samoa", "Oceania");
		countries_lowercase_continents_map.put("palau", "Oceania");
		countries_lowercase_continents_map.put("papua new guinea", "Oceania");
		countries_lowercase_continents_map.put("solomon islands", "Oceania");
		countries_lowercase_continents_map.put("kiribati", "Oceania");
		countries_lowercase_continents_map.put("marshall islands", "Oceania");
		countries_lowercase_continents_map.put("new caledonia", "Oceania");
		countries_lowercase_continents_map.put("norfolk island", "Oceania");
		countries_lowercase_continents_map.put("new zealand", "Oceania");
		countries_lowercase_continents_map.put("french polynesia", "Oceania");
		countries_lowercase_continents_map.put("pitcairn", "Oceania");
		countries_lowercase_continents_map.put("niue", "Oceania");
		countries_lowercase_continents_map.put("cocos islands", "Oceania");
		countries_lowercase_continents_map.put("united states minor outlying islands", "North America");
		countries_lowercase_continents_map.put("northern mariana islands", "Oceania");
		countries_lowercase_continents_map.put("east timor", "Oceania");
		countries_lowercase_continents_map.put("tuvalu", "Oceania");
		countries_lowercase_continents_map.put("vanuatu", "Oceania");
		countries_lowercase_continents_map.put("tonga", "Oceania");
		countries_lowercase_continents_map.put("wallis and futuna", "Oceania");
		countries_lowercase_continents_map.put("samoa", "Oceania");
		countries_lowercase_continents_map.put("angola", "Africa");
		countries_lowercase_continents_map.put("democratic republic of the congo", "Africa");
		countries_lowercase_continents_map.put("djibouti", "Africa");
		countries_lowercase_continents_map.put("central african republic", "Africa");
		countries_lowercase_continents_map.put("ethiopia", "Africa");
		countries_lowercase_continents_map.put("eritrea", "Africa");
		countries_lowercase_continents_map.put("egypt", "Africa");
		countries_lowercase_continents_map.put("burundi", "Africa");
		countries_lowercase_continents_map.put("botswana", "Africa");
		countries_lowercase_continents_map.put("cameroon", "Africa");
		countries_lowercase_continents_map.put("republic of the congo", "Africa");
		countries_lowercase_continents_map.put("ivory coast", "Africa");
		countries_lowercase_continents_map.put("ghana", "Africa");
		countries_lowercase_continents_map.put("equatorial guinea", "Africa");
		countries_lowercase_continents_map.put("burkina faso", "Africa");
		countries_lowercase_continents_map.put("guinea-bissau", "Africa");
		countries_lowercase_continents_map.put("benin", "Africa");
		countries_lowercase_continents_map.put("gabon", "Africa");
		countries_lowercase_continents_map.put("gambia", "Africa");
		countries_lowercase_continents_map.put("guinea", "Africa");
		countries_lowercase_continents_map.put("western sahara", "Africa");
		countries_lowercase_continents_map.put("algeria", "Africa");
		countries_lowercase_continents_map.put("cape verde", "Africa");
		countries_lowercase_continents_map.put("somalia", "Africa");
		countries_lowercase_continents_map.put("libya", "Africa");
		countries_lowercase_continents_map.put("kenya", "Africa");
		countries_lowercase_continents_map.put("rwanda", "Africa");
		countries_lowercase_continents_map.put("malawi", "Africa");
		countries_lowercase_continents_map.put("seychelles", "Africa");
		countries_lowercase_continents_map.put("chad", "Africa");
		countries_lowercase_continents_map.put("sudan", "Africa");
		countries_lowercase_continents_map.put("namibia", "Africa");
		countries_lowercase_continents_map.put("comoros", "Africa");
		countries_lowercase_continents_map.put("lesotho", "Africa");
		countries_lowercase_continents_map.put("mauritius", "Africa");
		countries_lowercase_continents_map.put("swaziland", "Africa");
		countries_lowercase_continents_map.put("reunion", "Africa");
		countries_lowercase_continents_map.put("mozambique", "Africa");
		countries_lowercase_continents_map.put("madagascar", "Africa");
		countries_lowercase_continents_map.put("senegal", "Africa");
		countries_lowercase_continents_map.put("liberia", "Africa");
		countries_lowercase_continents_map.put("nigeria", "Africa");
		countries_lowercase_continents_map.put("togo", "Africa");
		countries_lowercase_continents_map.put("mauritania", "Africa");
		countries_lowercase_continents_map.put("sierra leone", "Africa");
		countries_lowercase_continents_map.put("sao tome and principe", "Africa");
		countries_lowercase_continents_map.put("niger", "Africa");
		countries_lowercase_continents_map.put("mali", "Africa");
		countries_lowercase_continents_map.put("morocco", "Africa");
		countries_lowercase_continents_map.put("saint helena", "Africa");
		countries_lowercase_continents_map.put("tanzania", "Africa");
		countries_lowercase_continents_map.put("zambia", "Africa");
		countries_lowercase_continents_map.put("uganda", "Africa");
		countries_lowercase_continents_map.put("zimbabwe", "Africa");
		countries_lowercase_continents_map.put("mayotte", "Africa");
		countries_lowercase_continents_map.put("south africa", "Africa");
		countries_lowercase_continents_map.put("tunisia", "Africa");
		countries_lowercase_continents_map.put("cyprus", "Europe");
		countries_lowercase_continents_map.put("greece", "Europe");
		countries_lowercase_continents_map.put("albania", "Europe");
		countries_lowercase_continents_map.put("andorra", "Europe");
		countries_lowercase_continents_map.put("estonia", "Europe");
		countries_lowercase_continents_map.put("belarus", "Europe");
		countries_lowercase_continents_map.put("finland", "Europe");
		countries_lowercase_continents_map.put("hungary", "Europe");
		countries_lowercase_continents_map.put("bulgaria", "Europe");
		countries_lowercase_continents_map.put("gibraltar", "Europe");
		countries_lowercase_continents_map.put("spain", "Europe");
		countries_lowercase_continents_map.put("italy", "Europe");
		countries_lowercase_continents_map.put("austria", "Europe");
		countries_lowercase_continents_map.put("denmark", "Europe");
		countries_lowercase_continents_map.put("faroe islands", "Europe");
		countries_lowercase_continents_map.put("iceland", "Europe");
		countries_lowercase_continents_map.put("united kingdom", "Europe");
		countries_lowercase_continents_map.put("ireland", "Europe");
		countries_lowercase_continents_map.put("switzerland", "Europe");
		countries_lowercase_continents_map.put("belgium", "Europe");
		countries_lowercase_continents_map.put("germany", "Europe");
		countries_lowercase_continents_map.put("france", "Europe");
		countries_lowercase_continents_map.put("isle of man", "Europe");
		countries_lowercase_continents_map.put("guernsey", "Europe");
		countries_lowercase_continents_map.put("czech republic", "Europe");
		countries_lowercase_continents_map.put("croatia", "Europe");
		countries_lowercase_continents_map.put("bosnia and herzegovina", "Europe");
		countries_lowercase_continents_map.put("russia", "Europe");
		countries_lowercase_continents_map.put("latvia", "Europe");
		countries_lowercase_continents_map.put("lithuania", "Europe");
		countries_lowercase_continents_map.put("sweden", "Europe");
		countries_lowercase_continents_map.put("moldova", "Europe");
		countries_lowercase_continents_map.put("romania", "Europe");
		countries_lowercase_continents_map.put("slovakia", "Europe");
		countries_lowercase_continents_map.put("poland", "Europe");
		countries_lowercase_continents_map.put("norway", "Europe");
		countries_lowercase_continents_map.put("serbia", "Europe");
		countries_lowercase_continents_map.put("kosovo", "Europe");
		countries_lowercase_continents_map.put("macedonia", "Europe");
		countries_lowercase_continents_map.put("portugal", "Europe");
		countries_lowercase_continents_map.put("malta", "Europe");
		countries_lowercase_continents_map.put("svalbard and jan mayen", "Europe");
		countries_lowercase_continents_map.put("netherlands", "Europe");
		countries_lowercase_continents_map.put("luxembourg", "Europe");
		countries_lowercase_continents_map.put("monaco", "Europe");
		countries_lowercase_continents_map.put("liechtenstein", "Europe");
		countries_lowercase_continents_map.put("jersey", "Europe");
		countries_lowercase_continents_map.put("san marino", "Europe");
		countries_lowercase_continents_map.put("slovenia", "Europe");
		countries_lowercase_continents_map.put("montenegro", "Europe");
		countries_lowercase_continents_map.put("ukraine", "Europe");
		countries_lowercase_continents_map.put("vatican", "Europe");
		countries_lowercase_continents_map.put("iran", "Asia");
		countries_lowercase_continents_map.put("iraq", "Asia");
		countries_lowercase_continents_map.put("azerbaijan", "Asia");
		countries_lowercase_continents_map.put("armenia", "Asia");
		countries_lowercase_continents_map.put("israel", "Asia");
		countries_lowercase_continents_map.put("bahrain", "Asia");
		countries_lowercase_continents_map.put("united arab emirates", "Asia");
		countries_lowercase_continents_map.put("georgia", "Asia");
		countries_lowercase_continents_map.put("afghanistan", "Asia");
		countries_lowercase_continents_map.put("india", "Asia");
		countries_lowercase_continents_map.put("bangladesh", "Asia");
		countries_lowercase_continents_map.put("indonesia", "Asia");
		countries_lowercase_continents_map.put("bhutan", "Asia");
		countries_lowercase_continents_map.put("china", "Asia");
		countries_lowercase_continents_map.put("hong kong", "Asia");
		countries_lowercase_continents_map.put("brunei", "Asia");
		countries_lowercase_continents_map.put("christmas island", "Asia");
		countries_lowercase_continents_map.put("saudi arabia", "Asia");
		countries_lowercase_continents_map.put("syria", "Asia");
		countries_lowercase_continents_map.put("jordan", "Asia");
		countries_lowercase_continents_map.put("lebanon", "Asia");
		countries_lowercase_continents_map.put("palestinian territory", "Asia");
		countries_lowercase_continents_map.put("kuwait", "Asia");
		countries_lowercase_continents_map.put("oman", "Asia");
		countries_lowercase_continents_map.put("qatar", "Asia");
		countries_lowercase_continents_map.put("kazakhstan", "Asia");
		countries_lowercase_continents_map.put("pakistan", "Asia");
		countries_lowercase_continents_map.put("thailand", "Asia");
		countries_lowercase_continents_map.put("tajikistan", "Asia");
		countries_lowercase_continents_map.put("malaysia", "Asia");
		countries_lowercase_continents_map.put("kyrgyzstan", "Asia");
		countries_lowercase_continents_map.put("sri lanka", "Asia");
		countries_lowercase_continents_map.put("maldives", "Asia");
		countries_lowercase_continents_map.put("nepal", "Asia");
		countries_lowercase_continents_map.put("myanmar", "Asia");
		countries_lowercase_continents_map.put("mongolia", "Asia");
		countries_lowercase_continents_map.put("laos", "Asia");
		countries_lowercase_continents_map.put("philippines", "Asia");
		countries_lowercase_continents_map.put("macao", "Asia");
		countries_lowercase_continents_map.put("cambodia", "Asia");
		countries_lowercase_continents_map.put("south korea", "Asia");
		countries_lowercase_continents_map.put("japan", "Asia");
		countries_lowercase_continents_map.put("north korea", "Asia");
		countries_lowercase_continents_map.put("singapore", "Asia");
		countries_lowercase_continents_map.put("yemen", "Asia");
		countries_lowercase_continents_map.put("turkmenistan", "Asia");
		countries_lowercase_continents_map.put("turkey", "Asia");
		countries_lowercase_continents_map.put("uzbekistan", "Asia");
		countries_lowercase_continents_map.put("vietnam", "Asia");
		countries_lowercase_continents_map.put("taiwan", "Asia");
		countries_lowercase_continents_map.put("cocos islands", "Oceania");
		countries_lowercase_continents_map.put("united states minor outlying islands", "North America");
		countries_lowercase_continents_map.put("british indian ocean territory", "Asia");
		countries_lowercase_continents_map.put("nauru", "Oceania");
		countries_lowercase_continents_map.put("falkland islands", "South America");
		
		countries_lowercase_continents_map.put("Aaland Islands", "Europe");
		countries_lowercase_continents_map.put("Bouvet Island", "Antarctica");
		countries_lowercase_continents_map.put("Tokelau", "Oceania");
		countries_lowercase_continents_map.put("Serbia and Montenegro", "Europe");
		countries_lowercase_continents_map.put("Heard Island and McDonald Islands", "Antarctica");
	}
	
	private static void initialize_continents_list(){
		continents_list.add("Asia");
		continents_list.add("North America");
		continents_list.add("Europe");
		continents_list.add("Africa");
		continents_list.add("Antarctica");
		continents_list.add("South America");
		continents_list.add("Oceania");
	}
	
	private static void initialize_countries_list(){
		countries_list.add("Vanuatu");
		countries_list.add("Vietnam");
		countries_list.add("Ecuador");
		countries_list.add("U.S. Virgin Islands");
		countries_list.add("Algeria");
		countries_list.add("British Virgin Islands");
		countries_list.add("Venezuela");
		countries_list.add("Dominica");
		countries_list.add("Saint Vincent and the Grenadines");
		countries_list.add("Dominican Republic");
		countries_list.add("Vatican");
		countries_list.add("Germany");
		countries_list.add("Uzbekistan");
		countries_list.add("Uruguay");
		countries_list.add("Denmark");
		countries_list.add("Djibouti");
		countries_list.add("United States");
		countries_list.add("United States Minor Outlying Islands");
		countries_list.add("Uganda");
		countries_list.add("Ukraine");
		countries_list.add("Ethiopia");
		countries_list.add("Spain");
		countries_list.add("Eritrea");
		countries_list.add("Western Sahara");
		countries_list.add("Egypt");
		countries_list.add("Tanzania");
		countries_list.add("Estonia");
		countries_list.add("Trinidad and Tobago");
		countries_list.add("Taiwan");
		countries_list.add("Tuvalu");
		countries_list.add("Grenada");
		countries_list.add("Georgia");
		countries_list.add("French Guiana");
		countries_list.add("Gabon");
		countries_list.add("United Kingdom");
		countries_list.add("Kosovo");
		countries_list.add("France");
		countries_list.add("Faroe Islands");
		countries_list.add("Falkland Islands");
		countries_list.add("Fiji");
		countries_list.add("Micronesia");
		countries_list.add("Finland");
		countries_list.add("Samoa");
		countries_list.add("Guyana");
		countries_list.add("Guinea-Bissau");
		countries_list.add("Guam");
		countries_list.add("Guatemala");
		countries_list.add("South Georgia and the South Sandwich Islands");
		countries_list.add("Greece");
		countries_list.add("Equatorial Guinea");
		countries_list.add("Wallis and Futuna");
		countries_list.add("Guadeloupe");
		countries_list.add("Guinea");
		countries_list.add("Gambia");
		countries_list.add("Greenland");
		countries_list.add("Gibraltar");
		countries_list.add("Ghana");
		countries_list.add("Guernsey");
		countries_list.add("Reunion");
		countries_list.add("Romania");
		countries_list.add("Austria");
		countries_list.add("American Samoa");
		countries_list.add("Argentina");
		countries_list.add("Antarctica");
		countries_list.add("Aaland Islands");
		countries_list.add("Qatar");
		countries_list.add("Aruba");
		countries_list.add("Australia");
		countries_list.add("Azerbaijan");
		countries_list.add("Bosnia and Herzegovina");
		countries_list.add("Portugal");
		countries_list.add("Andorra");
		countries_list.add("Palau");
		countries_list.add("Antigua and Barbuda");
		countries_list.add("Puerto Rico");
		countries_list.add("United Arab Emirates");
		countries_list.add("Palestinian Territory");
		countries_list.add("Afghanistan");
		countries_list.add("Albania");
		countries_list.add("Anguilla");
		countries_list.add("Angola");
		countries_list.add("Paraguay");
		countries_list.add("Armenia");
		countries_list.add("Netherlands Antilles");
		countries_list.add("Togo");
		countries_list.add("Botswana");
		countries_list.add("French Southern Territories");
		countries_list.add("Bouvet Island");
		countries_list.add("Belarus");
		countries_list.add("Chad");
		countries_list.add("Tokelau");
		countries_list.add("Bahamas");
		countries_list.add("Tajikistan");
		countries_list.add("Brazil");
		countries_list.add("Thailand");
		countries_list.add("Bhutan");
		countries_list.add("Tonga");
		countries_list.add("Tunisia");
		countries_list.add("Turkmenistan");
		countries_list.add("East Timor");
		countries_list.add("Canada");
		countries_list.add("Turkey");
		countries_list.add("Belize");
		countries_list.add("Burkina Faso");
		countries_list.add("El Salvador");
		countries_list.add("Bulgaria");
		countries_list.add("Bahrain");
		countries_list.add("Sao Tome and Principe");
		countries_list.add("Burundi");
		countries_list.add("Syria");
		countries_list.add("Barbados");
		countries_list.add("Swaziland");
		countries_list.add("Bangladesh");
		countries_list.add("Belgium");
		countries_list.add("Brunei");
		countries_list.add("Bolivia");
		countries_list.add("Benin");
		countries_list.add("Turks and Caicos Islands");
		countries_list.add("Saint Barthelemy");
		countries_list.add("Bermuda");
		countries_list.add("Sudan");
		countries_list.add("Czech Republic");
		countries_list.add("Seychelles");
		countries_list.add("Cyprus");
		countries_list.add("Christmas Island");
		countries_list.add("Sweden");
		countries_list.add("Saint Helena");
		countries_list.add("Cape Verde");
		countries_list.add("Singapore");
		countries_list.add("Cuba");
		countries_list.add("Svalbard and Jan Mayen");
		countries_list.add("Slovenia");
		countries_list.add("Serbia and Montenegro");
		countries_list.add("Sierra Leone");
		countries_list.add("Slovakia");
		countries_list.add("Senegal");
		countries_list.add("San Marino");
		countries_list.add("Somalia");
		countries_list.add("Suriname");
		countries_list.add("Ivory Coast");
		countries_list.add("Serbia");
		countries_list.add("Republic of the Congo");
		countries_list.add("Russia");
		countries_list.add("Switzerland");
		countries_list.add("Rwanda");
		countries_list.add("Central African Republic");
		countries_list.add("Cocos Islands");
		countries_list.add("Democratic Republic of the Congo");
		countries_list.add("Costa Rica");
		countries_list.add("Colombia");
		countries_list.add("Cameroon");
		countries_list.add("China");
		countries_list.add("Saudi Arabia");
		countries_list.add("Cook Islands");
		countries_list.add("Solomon Islands");
		countries_list.add("Chile");
		countries_list.add("Latvia");
		countries_list.add("Luxembourg");
		countries_list.add("Lithuania");
		countries_list.add("Libya");
		countries_list.add("Lesotho");
		countries_list.add("Liberia");
		countries_list.add("Madagascar");
		countries_list.add("Marshall Islands");
		countries_list.add("Montenegro");
		countries_list.add("Saint Martin");
		countries_list.add("Macedonia");
		countries_list.add("Mali");
		countries_list.add("Monaco");
		countries_list.add("Moldova");
		countries_list.add("Morocco");
		countries_list.add("Maldives");
		countries_list.add("Mauritius");
		countries_list.add("Mexico");
		countries_list.add("Malawi");
		countries_list.add("Mozambique");
		countries_list.add("Malaysia");
		countries_list.add("Mongolia");
		countries_list.add("Myanmar");
		countries_list.add("Northern Mariana Islands");
		countries_list.add("Macao");
		countries_list.add("Mauritania");
		countries_list.add("Martinique");
		countries_list.add("Malta");
		countries_list.add("Montserrat");
		countries_list.add("Norfolk Island");
		countries_list.add("Nigeria");
		countries_list.add("Nicaragua");
		countries_list.add("Netherlands");
		countries_list.add("Namibia");
		countries_list.add("New Caledonia");
		countries_list.add("Niger");
		countries_list.add("New Zealand");
		countries_list.add("Niue");
		countries_list.add("Nauru");
		countries_list.add("Nepal");
		countries_list.add("Norway");
		countries_list.add("Oman");
		countries_list.add("Poland");
		countries_list.add("Saint Pierre and Miquelon");
		countries_list.add("Pitcairn");
		countries_list.add("Philippines");
		countries_list.add("Pakistan");
		countries_list.add("Peru");
		countries_list.add("French Polynesia");
		countries_list.add("Papua New Guinea");
		countries_list.add("Panama");
		countries_list.add("Hong Kong");
		countries_list.add("South Africa");
		countries_list.add("Honduras");
		countries_list.add("Heard Island and McDonald Islands");
		countries_list.add("Croatia");
		countries_list.add("Haiti");
		countries_list.add("Hungary");
		countries_list.add("Zambia");
		countries_list.add("Zimbabwe");
		countries_list.add("Indonesia");
		countries_list.add("Ireland");
		countries_list.add("Israel");
		countries_list.add("Isle of Man");
		countries_list.add("India");
		countries_list.add("British Indian Ocean Territory");
		countries_list.add("Iraq");
		countries_list.add("Iran");
		countries_list.add("Yemen");
		countries_list.add("Iceland");
		countries_list.add("Italy");
		countries_list.add("Jersey");
		countries_list.add("Mayotte");
		countries_list.add("Japan");
		countries_list.add("Jordan");
		countries_list.add("Jamaica");
		countries_list.add("Kiribati");
		countries_list.add("Cambodia");
		countries_list.add("Kyrgyzstan");
		countries_list.add("Kenya");
		countries_list.add("North Korea");
		countries_list.add("South Korea");
		countries_list.add("Comoros");
		countries_list.add("Saint Kitts and Nevis");
		countries_list.add("Kuwait");
		countries_list.add("Cayman Islands");
		countries_list.add("Kazakhstan");
		countries_list.add("Laos");
		countries_list.add("Saint Lucia");
		countries_list.add("Lebanon");
		countries_list.add("Liechtenstein");
		countries_list.add("Sri Lanka");
	}
	
	private static void initialize_countries_list_lowercase(){
		countries_list_lowercase.add("vanuatu");
		countries_list_lowercase.add("vietnam");
		countries_list_lowercase.add("ecuador");
		countries_list_lowercase.add("u.s. virgin islands");
		countries_list_lowercase.add("algeria");
		countries_list_lowercase.add("british virgin islands");
		countries_list_lowercase.add("venezuela");
		countries_list_lowercase.add("dominica");
		countries_list_lowercase.add("saint vincent and the grenadines");
		countries_list_lowercase.add("dominican republic");
		countries_list_lowercase.add("vatican");
		countries_list_lowercase.add("germany");
		countries_list_lowercase.add("uzbekistan");
		countries_list_lowercase.add("uruguay");
		countries_list_lowercase.add("denmark");
		countries_list_lowercase.add("djibouti");
		countries_list_lowercase.add("united states");
		countries_list_lowercase.add("united states minor outlying islands");
		countries_list_lowercase.add("uganda");
		countries_list_lowercase.add("ukraine");
		countries_list_lowercase.add("ethiopia");
		countries_list_lowercase.add("spain");
		countries_list_lowercase.add("eritrea");
		countries_list_lowercase.add("western sahara");
		countries_list_lowercase.add("egypt");
		countries_list_lowercase.add("tanzania");
		countries_list_lowercase.add("estonia");
		countries_list_lowercase.add("trinidad and tobago");
		countries_list_lowercase.add("taiwan");
		countries_list_lowercase.add("tuvalu");
		countries_list_lowercase.add("grenada");
		countries_list_lowercase.add("georgia");
		countries_list_lowercase.add("french guiana");
		countries_list_lowercase.add("gabon");
		countries_list_lowercase.add("united kingdom");
		countries_list_lowercase.add("kosovo");
		countries_list_lowercase.add("france");
		countries_list_lowercase.add("faroe islands");
		countries_list_lowercase.add("falkland islands");
		countries_list_lowercase.add("fiji");
		countries_list_lowercase.add("micronesia");
		countries_list_lowercase.add("finland");
		countries_list_lowercase.add("samoa");
		countries_list_lowercase.add("guyana");
		countries_list_lowercase.add("guinea-bissau");
		countries_list_lowercase.add("guam");
		countries_list_lowercase.add("guatemala");
		countries_list_lowercase.add("south georgia and the south sandwich islands");
		countries_list_lowercase.add("greece");
		countries_list_lowercase.add("equatorial guinea");
		countries_list_lowercase.add("wallis and futuna");
		countries_list_lowercase.add("guadeloupe");
		countries_list_lowercase.add("guinea");
		countries_list_lowercase.add("gambia");
		countries_list_lowercase.add("greenland");
		countries_list_lowercase.add("gibraltar");
		countries_list_lowercase.add("ghana");
		countries_list_lowercase.add("guernsey");
		countries_list_lowercase.add("reunion");
		countries_list_lowercase.add("romania");
		countries_list_lowercase.add("austria");
		countries_list_lowercase.add("american samoa");
		countries_list_lowercase.add("argentina");
		countries_list_lowercase.add("antarctica");
		countries_list_lowercase.add("aaland islands");
		countries_list_lowercase.add("qatar");
		countries_list_lowercase.add("aruba");
		countries_list_lowercase.add("australia");
		countries_list_lowercase.add("azerbaijan");
		countries_list_lowercase.add("bosnia and herzegovina");
		countries_list_lowercase.add("portugal");
		countries_list_lowercase.add("andorra");
		countries_list_lowercase.add("palau");
		countries_list_lowercase.add("antigua and barbuda");
		countries_list_lowercase.add("puerto rico");
		countries_list_lowercase.add("united arab emirates");
		countries_list_lowercase.add("palestinian territory");
		countries_list_lowercase.add("afghanistan");
		countries_list_lowercase.add("albania");
		countries_list_lowercase.add("anguilla");
		countries_list_lowercase.add("angola");
		countries_list_lowercase.add("paraguay");
		countries_list_lowercase.add("armenia");
		countries_list_lowercase.add("netherlands antilles");
		countries_list_lowercase.add("togo");
		countries_list_lowercase.add("botswana");
		countries_list_lowercase.add("french southern territories");
		countries_list_lowercase.add("bouvet island");
		countries_list_lowercase.add("belarus");
		countries_list_lowercase.add("chad");
		countries_list_lowercase.add("tokelau");
		countries_list_lowercase.add("bahamas");
		countries_list_lowercase.add("tajikistan");
		countries_list_lowercase.add("brazil");
		countries_list_lowercase.add("thailand");
		countries_list_lowercase.add("bhutan");
		countries_list_lowercase.add("tonga");
		countries_list_lowercase.add("tunisia");
		countries_list_lowercase.add("turkmenistan");
		countries_list_lowercase.add("east timor");
		countries_list_lowercase.add("canada");
		countries_list_lowercase.add("turkey");
		countries_list_lowercase.add("belize");
		countries_list_lowercase.add("burkina faso");
		countries_list_lowercase.add("el salvador");
		countries_list_lowercase.add("bulgaria");
		countries_list_lowercase.add("bahrain");
		countries_list_lowercase.add("sao tome and principe");
		countries_list_lowercase.add("burundi");
		countries_list_lowercase.add("syria");
		countries_list_lowercase.add("barbados");
		countries_list_lowercase.add("swaziland");
		countries_list_lowercase.add("bangladesh");
		countries_list_lowercase.add("belgium");
		countries_list_lowercase.add("brunei");
		countries_list_lowercase.add("bolivia");
		countries_list_lowercase.add("benin");
		countries_list_lowercase.add("turks and caicos islands");
		countries_list_lowercase.add("saint barthelemy");
		countries_list_lowercase.add("bermuda");
		countries_list_lowercase.add("sudan");
		countries_list_lowercase.add("czech republic");
		countries_list_lowercase.add("seychelles");
		countries_list_lowercase.add("cyprus");
		countries_list_lowercase.add("christmas island");
		countries_list_lowercase.add("sweden");
		countries_list_lowercase.add("saint helena");
		countries_list_lowercase.add("cape verde");
		countries_list_lowercase.add("singapore");
		countries_list_lowercase.add("cuba");
		countries_list_lowercase.add("svalbard and jan mayen");
		countries_list_lowercase.add("slovenia");
		countries_list_lowercase.add("serbia and montenegro");
		countries_list_lowercase.add("sierra leone");
		countries_list_lowercase.add("slovakia");
		countries_list_lowercase.add("senegal");
		countries_list_lowercase.add("san marino");
		countries_list_lowercase.add("somalia");
		countries_list_lowercase.add("suriname");
		countries_list_lowercase.add("ivory coast");
		countries_list_lowercase.add("serbia");
		countries_list_lowercase.add("republic of the congo");
		countries_list_lowercase.add("russia");
		countries_list_lowercase.add("switzerland");
		countries_list_lowercase.add("rwanda");
		countries_list_lowercase.add("central african republic");
		countries_list_lowercase.add("cocos islands");
		countries_list_lowercase.add("democratic republic of the congo");
		countries_list_lowercase.add("costa rica");
		countries_list_lowercase.add("colombia");
		countries_list_lowercase.add("cameroon");
		countries_list_lowercase.add("china");
		countries_list_lowercase.add("saudi arabia");
		countries_list_lowercase.add("cook islands");
		countries_list_lowercase.add("solomon islands");
		countries_list_lowercase.add("chile");
		countries_list_lowercase.add("latvia");
		countries_list_lowercase.add("luxembourg");
		countries_list_lowercase.add("lithuania");
		countries_list_lowercase.add("libya");
		countries_list_lowercase.add("lesotho");
		countries_list_lowercase.add("liberia");
		countries_list_lowercase.add("madagascar");
		countries_list_lowercase.add("marshall islands");
		countries_list_lowercase.add("montenegro");
		countries_list_lowercase.add("saint martin");
		countries_list_lowercase.add("macedonia");
		countries_list_lowercase.add("mali");
		countries_list_lowercase.add("monaco");
		countries_list_lowercase.add("moldova");
		countries_list_lowercase.add("morocco");
		countries_list_lowercase.add("maldives");
		countries_list_lowercase.add("mauritius");
		countries_list_lowercase.add("mexico");
		countries_list_lowercase.add("malawi");
		countries_list_lowercase.add("mozambique");
		countries_list_lowercase.add("malaysia");
		countries_list_lowercase.add("mongolia");
		countries_list_lowercase.add("myanmar");
		countries_list_lowercase.add("northern mariana islands");
		countries_list_lowercase.add("macao");
		countries_list_lowercase.add("mauritania");
		countries_list_lowercase.add("martinique");
		countries_list_lowercase.add("malta");
		countries_list_lowercase.add("montserrat");
		countries_list_lowercase.add("norfolk island");
		countries_list_lowercase.add("nigeria");
		countries_list_lowercase.add("nicaragua");
		countries_list_lowercase.add("netherlands");
		countries_list_lowercase.add("namibia");
		countries_list_lowercase.add("new caledonia");
		countries_list_lowercase.add("niger");
		countries_list_lowercase.add("new zealand");
		countries_list_lowercase.add("niue");
		countries_list_lowercase.add("nauru");
		countries_list_lowercase.add("nepal");
		countries_list_lowercase.add("norway");
		countries_list_lowercase.add("oman");
		countries_list_lowercase.add("poland");
		countries_list_lowercase.add("saint pierre and miquelon");
		countries_list_lowercase.add("pitcairn");
		countries_list_lowercase.add("philippines");
		countries_list_lowercase.add("pakistan");
		countries_list_lowercase.add("peru");
		countries_list_lowercase.add("french polynesia");
		countries_list_lowercase.add("papua new guinea");
		countries_list_lowercase.add("panama");
		countries_list_lowercase.add("hong kong");
		countries_list_lowercase.add("south africa");
		countries_list_lowercase.add("honduras");
		countries_list_lowercase.add("heard island and mcdonald islands");
		countries_list_lowercase.add("croatia");
		countries_list_lowercase.add("haiti");
		countries_list_lowercase.add("hungary");
		countries_list_lowercase.add("zambia");
		countries_list_lowercase.add("zimbabwe");
		countries_list_lowercase.add("indonesia");
		countries_list_lowercase.add("ireland");
		countries_list_lowercase.add("israel");
		countries_list_lowercase.add("isle of man");
		countries_list_lowercase.add("india");
		countries_list_lowercase.add("british indian ocean territory");
		countries_list_lowercase.add("iraq");
		countries_list_lowercase.add("iran");
		countries_list_lowercase.add("yemen");
		countries_list_lowercase.add("iceland");
		countries_list_lowercase.add("italy");
		countries_list_lowercase.add("jersey");
		countries_list_lowercase.add("mayotte");
		countries_list_lowercase.add("japan");
		countries_list_lowercase.add("jordan");
		countries_list_lowercase.add("jamaica");
		countries_list_lowercase.add("kiribati");
		countries_list_lowercase.add("cambodia");
		countries_list_lowercase.add("kyrgyzstan");
		countries_list_lowercase.add("kenya");
		countries_list_lowercase.add("north korea");
		countries_list_lowercase.add("south korea");
		countries_list_lowercase.add("comoros");
		countries_list_lowercase.add("saint kitts and nevis");
		countries_list_lowercase.add("kuwait");
		countries_list_lowercase.add("cayman islands");
		countries_list_lowercase.add("kazakhstan");
		countries_list_lowercase.add("laos");
		countries_list_lowercase.add("saint lucia");
		countries_list_lowercase.add("lebanon");
		countries_list_lowercase.add("liechtenstein");
		countries_list_lowercase.add("sri lanka");

	}
	
	public static List<String> RemoveContinents(List<String> countries){
		List<String> continents = new ArrayList<String>();
		for(String continent : continents_list){
			if(countries.contains(continent)){
				continents.add(continent);
				countries.remove(continent);
			}
		}
		return continents;
	}
	
	public static void main(String[] args) {
		System.out.println(AS.size() + NA.size() + SA.size() + EU.size() + OC.size() + AF.size() + AN.size());
		System.out.println(countries_lowercase_continents_map.size());
		System.out.println(countries_list.size());
		System.out.println(countries_list_lowercase.size());
		System.out.println(countries_shortname_map.size());
	}
}